services:
  - type: web
    name: ai-finder
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn main:app --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: TZ
        value: Asia/Seoul
    pythonVersion: 3.10.13
    autoDeploy: true
