services:
  - type: web
    name: aifinder
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-use-pep517 -r requirements.txt
    startCommand: gunicorn main:app
