services:
  - type: web
    name: aifinder
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-build-isolation -r requirements.txt
    startCommand: gunicorn main:app
