services:
  - type: web
    name: aifinder
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --upgrade -r requirements.txt
    startCommand: gunicorn main:app
    build:
      pythonVersion: 3.11.6
